//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorConduccion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juegos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juegos()
        {
            this.Turnos = new HashSet<Turnos>();
        }
    
        public int JuegoId { get; set; }
        public int UsuarioId { get; set; }
        public int VehiculoId { get; set; }
        public int PistaId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public string Estado { get; set; }
    
        public virtual Pistas Pistas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turnos> Turnos { get; set; }
    }
}
