//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorConduccion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        public int TurnoId { get; set; }
        public int JuegoId { get; set; }
        public int NumeroTurno { get; set; }
        public string Accion { get; set; }
        public int Velocidad { get; set; }
        public int Carril { get; set; }
    
        public virtual Juegos Juegos { get; set; }
    }
}
